### ISSUE TITLE
Questions and features request: WS-Security Support

### ISSUE THREAD

**Issue by avioren** [CompassSecurity/SAMLRaider#38]
Hi.

I have noticed there is a limitation written to the tool:
"Bypassing XML signatures in non-SAML contexts, for example SOAP endpoints using WS-Security extensions."

I have encountered a situation I need to comply with this limitation...
Can you please direct me on how to develop/fix this limitation?

Thanks in advance,
Avi.

**Comment by mindfuckup** [comment]
Hi Avi

Thanks for your message.

At the moment, the parameter names are hardcoded. This can be found here: https://github.com/SAMLRaider/SAMLRaider/blob/master/src/main/java/application/SamlTabController.java#L297

A quick and dirty hack would be to chain two Burp instances where the 1st modifies the request on-the-fly so that the SAMLRaider plugin in the 2nd instance correctly detects the SAML Message.

Does this help?

Best wishes,
Emanuel

**Comment by mindfuckup** [comment]
SOAP and WSS is already supported.
