### ISSUE TITLE
Clone Certificate does not work if S/N is negative

### ISSUE THREAD

**Issue by emanuelduss** [CompassSecurity/SAMLRaider#40]
It's not possible to clone the certificate if the serial number of the certificate is negative.

**Comment by yobroda** [comment]
Hey awesome creators of this tool, I am also not able to proceed ahead as my certificate is not cloning due to negative serial numbers. Till the issue is fixed in the tool, can you please assist me by telling me on how to clone a certificate with negative serial number with some other way. This would be very helpful during my testing.

**Comment by mindfuckup** [comment]
Hi yobroda

There are other possibilities to create a fake certificate or clone a certificate.

1) Create a new CA and issue a new certificate. You can use the following script and adjust the values to your needs: https://github.com/mindfuckup/Scripts/blob/master/makecert


2) You can also clone certificates by reading the original certificate and create new key material. You can e.g. use the following code: https://twitter.com/guedou/status/1091349140636864517

Best wishes, 
Emanuel

**Comment by mindfuckup** [comment]
Hi yobroda

You can simply clone a certificate using PowerShell:

```powershell
$original = "c:\tmp\certificate.pem"
$cloned = "c:\tmp\cloned.p12"
$password = "Password-1234"

$cert_original = New-Object System.Security.Cryptography.X509Certificates.X509Certificate2
$cert_original.Import($original)
$export_password = ConvertTo-SecureString -String $password -Force -AsPlainText
$cert_cloned = New-SelfSignedCertificate -CloneCert $cert_original -CertStoreLocation "Cert:\CurrentUser\My\"
$cert_cloned | Export-PfxCertificate -FilePath $cloned -Password $export_password
Remove-Item $cert_cloned.PSPath
```

Have fun ;-)

Emanuel

**Comment by yobroda** [comment]
Thanks for the explanation!

**Comment by emanuelduss** [comment]
BTW i recently discovered the `clone-cert` script, which does the same on Linux. Either specify a TLS server with port or a local certificate to clone:  https://github.com/SySS-Research/clone-cert

Works really well :)

**Comment by yobroda** [comment]
Great, i will try this out !!

**Comment by t-hg** [comment]
RFC 5280 explicitly states that the serial number must be a positive integer, and this is enforced by the library (bouncy castle) used to generate the certificate.

>    The serial number MUST be a positive integer assigned by the CA to
   each certificate.  It MUST be unique for each certificate issued by a
   given CA (i.e., the issuer name and serial number identify a unique
   certificate).  CAs MUST force the serialNumber to be a non-negative
   integer.

[https://datatracker.ietf.org/doc/html/rfc5280](https://datatracker.ietf.org/doc/html/rfc5280)

To fix this, we would need to use a different library to generate the certificate. But I assume that this problem is rare. So I am not going to fix right now If you experience this problem, try the workaround above.
