### ISSUE TITLE
Intercept Tab - Can Only Change Raw XML, not Prettified

### ISSUE THREAD

**Issue by edmacke** [CompassSecurity/SAMLRaider#53]
When I intercept a SAML response, I can alter the XML in the "SAML Attacks" tab, but not the "SAML Message Info" tab's "Parsed & Prettified" XML.

In previous versions, I believe the XML was always prettified, and modifiable... that was much easier.

**Comment by mindfuckup** [comment]
This is the new behavior of the latest version and is intended.

This change was needed, because if the XML is prettified, the XML gets parsed, which would you not allow to perform XXE attacks anymore. This was also the reason, why the Parsed & Prettified XML in the SAML Message Info tab was introduced. So, at least you can still *view* the prettified version.

So, the XML is now not parsed anymore when displayed and exactly displayed how it was received. This gives you more control over the attacks. Additionally, if the raw mode is enabled, you can also see how exactly the XML is sent to the server.

**Comment by mindfuckup** [comment]
This is the new behavior of the latest version and is intended.

This change was needed, because if the XML is prettified, the XML gets parsed, which would you not allow to perform XXE attacks anymore. This was also the reason, why the Parsed & Prettified XML in the SAML Message Info tab was introduced. So, at least you can still *view* the prettified version.

So, the XML is now not parsed anymore when displayed and exactly displayed how it was received. This gives you more control over the attacks. Additionally, if the raw mode is enabled, you can also see how exactly the XML is sent to the server.
