### ISSUE TITLE
Signing takes forever...

### ISSUE THREAD

**Issue by legendOfZelda** [CompassSecurity/SAMLRaider#63]
Trying to resign a SAMLResponse with a self-signed certificate clone but the signing takes forever:
![image](https://user-images.githubusercontent.com/62873103/172189752-e4579253-12bc-4462-bf01-53099d307b8d.png)

**Comment by emanuelduss** [comment]
Hi

This is a known problem.

See issue https://github.com/CompassSecurity/SAMLRaider/issues/60 for more details.

It's fixed in release v1.4.1 (https://github.com/CompassSecurity/SAMLRaider/releases/tag/v1.4.1) but this release is not yet in the BApp store. Should be there soon. In the meanwhile, you can use the JAR file directly.

**Comment by emanuelduss** [comment]
The BApp store is now updated. You can get the latest version directly via Burp: https://portswigger.net/bappstore/c61cfa893bb14db4b01775554f7b802e

**Comment by emanuelduss** [comment]
If this bug does happen again in the latest version, please re-open the issue and provide the SAMLRequest so I can investigate it further.
